/*
 * generated by Xtext 2.12.0
 */
package rat


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class RatRuntimeModule extends AbstractRatRuntimeModule {
}
