/**
 * generated by Xtext 2.12.0
 */
package rat.rat.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import rat.rat.Appel;
import rat.rat.CP;
import rat.rat.RatPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Appel</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link rat.rat.impl.AppelImpl#getNomAppel <em>Nom Appel</em>}</li>
 *   <li>{@link rat.rat.impl.AppelImpl#getParam <em>Param</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AppelImpl extends EImpl implements Appel
{
  /**
   * The default value of the '{@link #getNomAppel() <em>Nom Appel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNomAppel()
   * @generated
   * @ordered
   */
  protected static final String NOM_APPEL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNomAppel() <em>Nom Appel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNomAppel()
   * @generated
   * @ordered
   */
  protected String nomAppel = NOM_APPEL_EDEFAULT;

  /**
   * The cached value of the '{@link #getParam() <em>Param</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParam()
   * @generated
   * @ordered
   */
  protected EList<CP> param;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AppelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RatPackage.Literals.APPEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getNomAppel()
  {
    return nomAppel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNomAppel(String newNomAppel)
  {
    String oldNomAppel = nomAppel;
    nomAppel = newNomAppel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RatPackage.APPEL__NOM_APPEL, oldNomAppel, nomAppel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<CP> getParam()
  {
    if (param == null)
    {
      param = new EObjectContainmentEList<CP>(CP.class, this, RatPackage.APPEL__PARAM);
    }
    return param;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RatPackage.APPEL__PARAM:
        return ((InternalEList<?>)getParam()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RatPackage.APPEL__NOM_APPEL:
        return getNomAppel();
      case RatPackage.APPEL__PARAM:
        return getParam();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RatPackage.APPEL__NOM_APPEL:
        setNomAppel((String)newValue);
        return;
      case RatPackage.APPEL__PARAM:
        getParam().clear();
        getParam().addAll((Collection<? extends CP>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RatPackage.APPEL__NOM_APPEL:
        setNomAppel(NOM_APPEL_EDEFAULT);
        return;
      case RatPackage.APPEL__PARAM:
        getParam().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RatPackage.APPEL__NOM_APPEL:
        return NOM_APPEL_EDEFAULT == null ? nomAppel != null : !NOM_APPEL_EDEFAULT.equals(nomAppel);
      case RatPackage.APPEL__PARAM:
        return param != null && !param.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (nomAppel: ");
    result.append(nomAppel);
    result.append(')');
    return result.toString();
  }

} //AppelImpl
