/**
 * generated by Xtext 2.12.0
 */
package rat.rat;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link rat.rat.Boolean#getB <em>B</em>}</li>
 * </ul>
 *
 * @see rat.rat.RatPackage#getBoolean()
 * @model
 * @generated
 */
public interface Boolean extends E
{
  /**
   * Returns the value of the '<em><b>B</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>B</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>B</em>' attribute.
   * @see #setB(String)
   * @see rat.rat.RatPackage#getBoolean_B()
   * @model
   * @generated
   */
  String getB();

  /**
   * Sets the value of the '{@link rat.rat.Boolean#getB <em>B</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>B</em>' attribute.
   * @see #getB()
   * @generated
   */
  void setB(String value);

} // Boolean
