/**
 * generated by Xtext 2.12.0
 */
package rat.rat;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constante</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link rat.rat.Constante#getNom <em>Nom</em>}</li>
 *   <li>{@link rat.rat.Constante#getE <em>E</em>}</li>
 * </ul>
 *
 * @see rat.rat.RatPackage#getConstante()
 * @model
 * @generated
 */
public interface Constante extends I
{
  /**
   * Returns the value of the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nom</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nom</em>' attribute.
   * @see #setNom(String)
   * @see rat.rat.RatPackage#getConstante_Nom()
   * @model
   * @generated
   */
  String getNom();

  /**
   * Sets the value of the '{@link rat.rat.Constante#getNom <em>Nom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nom</em>' attribute.
   * @see #getNom()
   * @generated
   */
  void setNom(String value);

  /**
   * Returns the value of the '<em><b>E</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>E</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>E</em>' attribute.
   * @see #setE(int)
   * @see rat.rat.RatPackage#getConstante_E()
   * @model
   * @generated
   */
  int getE();

  /**
   * Sets the value of the '{@link rat.rat.Constante#getE <em>E</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>E</em>' attribute.
   * @see #getE()
   * @generated
   */
  void setE(int value);

} // Constante
