/**
 * generated by Xtext 2.12.0
 */
package rat.rat;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>E</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see rat.rat.RatPackage#getE()
 * @model
 * @generated
 */
public interface E extends EObject
{
} // E
