/**
 * generated by Xtext 2.12.0
 */
package rat.rat;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operande</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link rat.rat.Operande#getOp <em>Op</em>}</li>
 * </ul>
 *
 * @see rat.rat.RatPackage#getOperande()
 * @model
 * @generated
 */
public interface Operande extends EObject
{
  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Op</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see rat.rat.RatPackage#getOperande_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link rat.rat.Operande#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

} // Operande
