/**
 * generated by Xtext 2.12.0
 */
package rat.rat;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see rat.rat.RatFactory
 * @model kind="package"
 * @generated
 */
public interface RatPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "rat";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.Rat.rat";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "rat";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RatPackage eINSTANCE = rat.rat.impl.RatPackageImpl.init();

  /**
   * The meta object id for the '{@link rat.rat.impl.ProgImpl <em>Prog</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.ProgImpl
   * @see rat.rat.impl.RatPackageImpl#getProg()
   * @generated
   */
  int PROG = 0;

  /**
   * The feature id for the '<em><b>Fun</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROG__FUN = 0;

  /**
   * The feature id for the '<em><b>Bloc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROG__BLOC = 1;

  /**
   * The number of structural features of the '<em>Prog</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROG_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link rat.rat.impl.FunImpl <em>Fun</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.FunImpl
   * @see rat.rat.impl.RatPackageImpl#getFun()
   * @generated
   */
  int FUN = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUN__TYPE = 0;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUN__NOM = 1;

  /**
   * The feature id for the '<em><b>Param</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUN__PARAM = 2;

  /**
   * The feature id for the '<em><b>Is</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUN__IS = 3;

  /**
   * The feature id for the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUN__E = 4;

  /**
   * The number of structural features of the '<em>Fun</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUN_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link rat.rat.impl.BlocImpl <em>Bloc</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.BlocImpl
   * @see rat.rat.impl.RatPackageImpl#getBloc()
   * @generated
   */
  int BLOC = 2;

  /**
   * The feature id for the '<em><b>Is</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOC__IS = 0;

  /**
   * The number of structural features of the '<em>Bloc</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOC_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link rat.rat.impl.IImpl <em>I</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.IImpl
   * @see rat.rat.impl.RatPackageImpl#getI()
   * @generated
   */
  int I = 3;

  /**
   * The number of structural features of the '<em>I</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int I_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link rat.rat.impl.DeclarationImpl <em>Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.DeclarationImpl
   * @see rat.rat.impl.RatPackageImpl#getDeclaration()
   * @generated
   */
  int DECLARATION = 4;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__TYPE = I_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__NOM = I_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__E = I_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_FEATURE_COUNT = I_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link rat.rat.impl.AffectationImpl <em>Affectation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.AffectationImpl
   * @see rat.rat.impl.RatPackageImpl#getAffectation()
   * @generated
   */
  int AFFECTATION = 5;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION__NOM = I_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION__E = I_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Affectation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION_FEATURE_COUNT = I_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link rat.rat.impl.ConstanteImpl <em>Constante</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.ConstanteImpl
   * @see rat.rat.impl.RatPackageImpl#getConstante()
   * @generated
   */
  int CONSTANTE = 6;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANTE__NOM = I_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>E</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANTE__E = I_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Constante</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANTE_FEATURE_COUNT = I_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link rat.rat.impl.PrintImpl <em>Print</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.PrintImpl
   * @see rat.rat.impl.RatPackageImpl#getPrint()
   * @generated
   */
  int PRINT = 7;

  /**
   * The feature id for the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT__E = I_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Print</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_FEATURE_COUNT = I_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link rat.rat.impl.ConditionnelleImpl <em>Conditionnelle</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.ConditionnelleImpl
   * @see rat.rat.impl.RatPackageImpl#getConditionnelle()
   * @generated
   */
  int CONDITIONNELLE = 8;

  /**
   * The feature id for the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONNELLE__E = I_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Bloc1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONNELLE__BLOC1 = I_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Bloc2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONNELLE__BLOC2 = I_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Conditionnelle</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONNELLE_FEATURE_COUNT = I_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link rat.rat.impl.TantqueImpl <em>Tantque</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.TantqueImpl
   * @see rat.rat.impl.RatPackageImpl#getTantque()
   * @generated
   */
  int TANTQUE = 9;

  /**
   * The feature id for the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TANTQUE__E = I_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Bloc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TANTQUE__BLOC = I_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Tantque</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TANTQUE_FEATURE_COUNT = I_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link rat.rat.impl.DPImpl <em>DP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.DPImpl
   * @see rat.rat.impl.RatPackageImpl#getDP()
   * @generated
   */
  int DP = 10;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DP__TYPE = 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DP__ID = 1;

  /**
   * The number of structural features of the '<em>DP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link rat.rat.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.TypeImpl
   * @see rat.rat.impl.RatPackageImpl#getType()
   * @generated
   */
  int TYPE = 11;

  /**
   * The feature id for the '<em><b>T</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__T = 0;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link rat.rat.impl.CPImpl <em>CP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.CPImpl
   * @see rat.rat.impl.RatPackageImpl#getCP()
   * @generated
   */
  int CP = 12;

  /**
   * The feature id for the '<em><b>E</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CP__E = 0;

  /**
   * The number of structural features of the '<em>CP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link rat.rat.impl.EImpl <em>E</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.EImpl
   * @see rat.rat.impl.RatPackageImpl#getE()
   * @generated
   */
  int E = 13;

  /**
   * The number of structural features of the '<em>E</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int E_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link rat.rat.impl.AppelImpl <em>Appel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.AppelImpl
   * @see rat.rat.impl.RatPackageImpl#getAppel()
   * @generated
   */
  int APPEL = 14;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPEL__NOM = E_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Param</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPEL__PARAM = E_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Appel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPEL_FEATURE_COUNT = E_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link rat.rat.impl.RationnelImpl <em>Rationnel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.RationnelImpl
   * @see rat.rat.impl.RatPackageImpl#getRationnel()
   * @generated
   */
  int RATIONNEL = 15;

  /**
   * The feature id for the '<em><b>E1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RATIONNEL__E1 = E_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>E2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RATIONNEL__E2 = E_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Rationnel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RATIONNEL_FEATURE_COUNT = E_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link rat.rat.impl.NumerateurImpl <em>Numerateur</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.NumerateurImpl
   * @see rat.rat.impl.RatPackageImpl#getNumerateur()
   * @generated
   */
  int NUMERATEUR = 16;

  /**
   * The feature id for the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMERATEUR__E = E_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Numerateur</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMERATEUR_FEATURE_COUNT = E_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link rat.rat.impl.DenominateurImpl <em>Denominateur</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.DenominateurImpl
   * @see rat.rat.impl.RatPackageImpl#getDenominateur()
   * @generated
   */
  int DENOMINATEUR = 17;

  /**
   * The feature id for the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DENOMINATEUR__E = E_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Denominateur</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DENOMINATEUR_FEATURE_COUNT = E_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link rat.rat.impl.IdentificateurImpl <em>Identificateur</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.IdentificateurImpl
   * @see rat.rat.impl.RatPackageImpl#getIdentificateur()
   * @generated
   */
  int IDENTIFICATEUR = 18;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENTIFICATEUR__ID = E_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Identificateur</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENTIFICATEUR_FEATURE_COUNT = E_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link rat.rat.impl.BooleanImpl <em>Boolean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.BooleanImpl
   * @see rat.rat.impl.RatPackageImpl#getBoolean()
   * @generated
   */
  int BOOLEAN = 19;

  /**
   * The feature id for the '<em><b>B</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN__B = E_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Boolean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_FEATURE_COUNT = E_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link rat.rat.impl.EntierImpl <em>Entier</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.EntierImpl
   * @see rat.rat.impl.RatPackageImpl#getEntier()
   * @generated
   */
  int ENTIER = 20;

  /**
   * The feature id for the '<em><b>Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIER__INT = E_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Entier</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIER_FEATURE_COUNT = E_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link rat.rat.impl.OpBinImpl <em>Op Bin</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.OpBinImpl
   * @see rat.rat.impl.RatPackageImpl#getOpBin()
   * @generated
   */
  int OP_BIN = 21;

  /**
   * The feature id for the '<em><b>E1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_BIN__E1 = E_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_BIN__OP = E_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>E2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_BIN__E2 = E_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Op Bin</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_BIN_FEATURE_COUNT = E_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link rat.rat.impl.OperandeImpl <em>Operande</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see rat.rat.impl.OperandeImpl
   * @see rat.rat.impl.RatPackageImpl#getOperande()
   * @generated
   */
  int OPERANDE = 22;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERANDE__OP = 0;

  /**
   * The number of structural features of the '<em>Operande</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERANDE_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link rat.rat.Prog <em>Prog</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Prog</em>'.
   * @see rat.rat.Prog
   * @generated
   */
  EClass getProg();

  /**
   * Returns the meta object for the containment reference list '{@link rat.rat.Prog#getFun <em>Fun</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fun</em>'.
   * @see rat.rat.Prog#getFun()
   * @see #getProg()
   * @generated
   */
  EReference getProg_Fun();

  /**
   * Returns the meta object for the containment reference '{@link rat.rat.Prog#getBloc <em>Bloc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bloc</em>'.
   * @see rat.rat.Prog#getBloc()
   * @see #getProg()
   * @generated
   */
  EReference getProg_Bloc();

  /**
   * Returns the meta object for class '{@link rat.rat.Fun <em>Fun</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fun</em>'.
   * @see rat.rat.Fun
   * @generated
   */
  EClass getFun();

  /**
   * Returns the meta object for the containment reference '{@link rat.rat.Fun#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see rat.rat.Fun#getType()
   * @see #getFun()
   * @generated
   */
  EReference getFun_Type();

  /**
   * Returns the meta object for the attribute '{@link rat.rat.Fun#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see rat.rat.Fun#getNom()
   * @see #getFun()
   * @generated
   */
  EAttribute getFun_Nom();

  /**
   * Returns the meta object for the containment reference list '{@link rat.rat.Fun#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Param</em>'.
   * @see rat.rat.Fun#getParam()
   * @see #getFun()
   * @generated
   */
  EReference getFun_Param();

  /**
   * Returns the meta object for the containment reference list '{@link rat.rat.Fun#getIs <em>Is</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Is</em>'.
   * @see rat.rat.Fun#getIs()
   * @see #getFun()
   * @generated
   */
  EReference getFun_Is();

  /**
   * Returns the meta object for the containment reference '{@link rat.rat.Fun#getE <em>E</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E</em>'.
   * @see rat.rat.Fun#getE()
   * @see #getFun()
   * @generated
   */
  EReference getFun_E();

  /**
   * Returns the meta object for class '{@link rat.rat.Bloc <em>Bloc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bloc</em>'.
   * @see rat.rat.Bloc
   * @generated
   */
  EClass getBloc();

  /**
   * Returns the meta object for the containment reference list '{@link rat.rat.Bloc#getIs <em>Is</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Is</em>'.
   * @see rat.rat.Bloc#getIs()
   * @see #getBloc()
   * @generated
   */
  EReference getBloc_Is();

  /**
   * Returns the meta object for class '{@link rat.rat.I <em>I</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>I</em>'.
   * @see rat.rat.I
   * @generated
   */
  EClass getI();

  /**
   * Returns the meta object for class '{@link rat.rat.Declaration <em>Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaration</em>'.
   * @see rat.rat.Declaration
   * @generated
   */
  EClass getDeclaration();

  /**
   * Returns the meta object for the containment reference '{@link rat.rat.Declaration#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see rat.rat.Declaration#getType()
   * @see #getDeclaration()
   * @generated
   */
  EReference getDeclaration_Type();

  /**
   * Returns the meta object for the attribute '{@link rat.rat.Declaration#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see rat.rat.Declaration#getNom()
   * @see #getDeclaration()
   * @generated
   */
  EAttribute getDeclaration_Nom();

  /**
   * Returns the meta object for the containment reference '{@link rat.rat.Declaration#getE <em>E</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E</em>'.
   * @see rat.rat.Declaration#getE()
   * @see #getDeclaration()
   * @generated
   */
  EReference getDeclaration_E();

  /**
   * Returns the meta object for class '{@link rat.rat.Affectation <em>Affectation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Affectation</em>'.
   * @see rat.rat.Affectation
   * @generated
   */
  EClass getAffectation();

  /**
   * Returns the meta object for the attribute '{@link rat.rat.Affectation#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see rat.rat.Affectation#getNom()
   * @see #getAffectation()
   * @generated
   */
  EAttribute getAffectation_Nom();

  /**
   * Returns the meta object for the containment reference '{@link rat.rat.Affectation#getE <em>E</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E</em>'.
   * @see rat.rat.Affectation#getE()
   * @see #getAffectation()
   * @generated
   */
  EReference getAffectation_E();

  /**
   * Returns the meta object for class '{@link rat.rat.Constante <em>Constante</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constante</em>'.
   * @see rat.rat.Constante
   * @generated
   */
  EClass getConstante();

  /**
   * Returns the meta object for the attribute '{@link rat.rat.Constante#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see rat.rat.Constante#getNom()
   * @see #getConstante()
   * @generated
   */
  EAttribute getConstante_Nom();

  /**
   * Returns the meta object for the attribute '{@link rat.rat.Constante#getE <em>E</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>E</em>'.
   * @see rat.rat.Constante#getE()
   * @see #getConstante()
   * @generated
   */
  EAttribute getConstante_E();

  /**
   * Returns the meta object for class '{@link rat.rat.Print <em>Print</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Print</em>'.
   * @see rat.rat.Print
   * @generated
   */
  EClass getPrint();

  /**
   * Returns the meta object for the containment reference '{@link rat.rat.Print#getE <em>E</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E</em>'.
   * @see rat.rat.Print#getE()
   * @see #getPrint()
   * @generated
   */
  EReference getPrint_E();

  /**
   * Returns the meta object for class '{@link rat.rat.Conditionnelle <em>Conditionnelle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Conditionnelle</em>'.
   * @see rat.rat.Conditionnelle
   * @generated
   */
  EClass getConditionnelle();

  /**
   * Returns the meta object for the containment reference '{@link rat.rat.Conditionnelle#getE <em>E</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E</em>'.
   * @see rat.rat.Conditionnelle#getE()
   * @see #getConditionnelle()
   * @generated
   */
  EReference getConditionnelle_E();

  /**
   * Returns the meta object for the containment reference '{@link rat.rat.Conditionnelle#getBloc1 <em>Bloc1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bloc1</em>'.
   * @see rat.rat.Conditionnelle#getBloc1()
   * @see #getConditionnelle()
   * @generated
   */
  EReference getConditionnelle_Bloc1();

  /**
   * Returns the meta object for the containment reference '{@link rat.rat.Conditionnelle#getBloc2 <em>Bloc2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bloc2</em>'.
   * @see rat.rat.Conditionnelle#getBloc2()
   * @see #getConditionnelle()
   * @generated
   */
  EReference getConditionnelle_Bloc2();

  /**
   * Returns the meta object for class '{@link rat.rat.Tantque <em>Tantque</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tantque</em>'.
   * @see rat.rat.Tantque
   * @generated
   */
  EClass getTantque();

  /**
   * Returns the meta object for the containment reference '{@link rat.rat.Tantque#getE <em>E</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E</em>'.
   * @see rat.rat.Tantque#getE()
   * @see #getTantque()
   * @generated
   */
  EReference getTantque_E();

  /**
   * Returns the meta object for the containment reference '{@link rat.rat.Tantque#getBloc <em>Bloc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bloc</em>'.
   * @see rat.rat.Tantque#getBloc()
   * @see #getTantque()
   * @generated
   */
  EReference getTantque_Bloc();

  /**
   * Returns the meta object for class '{@link rat.rat.DP <em>DP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DP</em>'.
   * @see rat.rat.DP
   * @generated
   */
  EClass getDP();

  /**
   * Returns the meta object for the containment reference '{@link rat.rat.DP#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see rat.rat.DP#getType()
   * @see #getDP()
   * @generated
   */
  EReference getDP_Type();

  /**
   * Returns the meta object for the attribute '{@link rat.rat.DP#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see rat.rat.DP#getId()
   * @see #getDP()
   * @generated
   */
  EAttribute getDP_Id();

  /**
   * Returns the meta object for class '{@link rat.rat.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see rat.rat.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the attribute '{@link rat.rat.Type#getT <em>T</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>T</em>'.
   * @see rat.rat.Type#getT()
   * @see #getType()
   * @generated
   */
  EAttribute getType_T();

  /**
   * Returns the meta object for class '{@link rat.rat.CP <em>CP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CP</em>'.
   * @see rat.rat.CP
   * @generated
   */
  EClass getCP();

  /**
   * Returns the meta object for the containment reference list '{@link rat.rat.CP#getE <em>E</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>E</em>'.
   * @see rat.rat.CP#getE()
   * @see #getCP()
   * @generated
   */
  EReference getCP_E();

  /**
   * Returns the meta object for class '{@link rat.rat.E <em>E</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>E</em>'.
   * @see rat.rat.E
   * @generated
   */
  EClass getE();

  /**
   * Returns the meta object for class '{@link rat.rat.Appel <em>Appel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Appel</em>'.
   * @see rat.rat.Appel
   * @generated
   */
  EClass getAppel();

  /**
   * Returns the meta object for the attribute '{@link rat.rat.Appel#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see rat.rat.Appel#getNom()
   * @see #getAppel()
   * @generated
   */
  EAttribute getAppel_Nom();

  /**
   * Returns the meta object for the containment reference list '{@link rat.rat.Appel#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Param</em>'.
   * @see rat.rat.Appel#getParam()
   * @see #getAppel()
   * @generated
   */
  EReference getAppel_Param();

  /**
   * Returns the meta object for class '{@link rat.rat.Rationnel <em>Rationnel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rationnel</em>'.
   * @see rat.rat.Rationnel
   * @generated
   */
  EClass getRationnel();

  /**
   * Returns the meta object for the containment reference '{@link rat.rat.Rationnel#getE1 <em>E1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E1</em>'.
   * @see rat.rat.Rationnel#getE1()
   * @see #getRationnel()
   * @generated
   */
  EReference getRationnel_E1();

  /**
   * Returns the meta object for the containment reference '{@link rat.rat.Rationnel#getE2 <em>E2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E2</em>'.
   * @see rat.rat.Rationnel#getE2()
   * @see #getRationnel()
   * @generated
   */
  EReference getRationnel_E2();

  /**
   * Returns the meta object for class '{@link rat.rat.Numerateur <em>Numerateur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Numerateur</em>'.
   * @see rat.rat.Numerateur
   * @generated
   */
  EClass getNumerateur();

  /**
   * Returns the meta object for the containment reference '{@link rat.rat.Numerateur#getE <em>E</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E</em>'.
   * @see rat.rat.Numerateur#getE()
   * @see #getNumerateur()
   * @generated
   */
  EReference getNumerateur_E();

  /**
   * Returns the meta object for class '{@link rat.rat.Denominateur <em>Denominateur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Denominateur</em>'.
   * @see rat.rat.Denominateur
   * @generated
   */
  EClass getDenominateur();

  /**
   * Returns the meta object for the containment reference '{@link rat.rat.Denominateur#getE <em>E</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E</em>'.
   * @see rat.rat.Denominateur#getE()
   * @see #getDenominateur()
   * @generated
   */
  EReference getDenominateur_E();

  /**
   * Returns the meta object for class '{@link rat.rat.Identificateur <em>Identificateur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Identificateur</em>'.
   * @see rat.rat.Identificateur
   * @generated
   */
  EClass getIdentificateur();

  /**
   * Returns the meta object for the attribute '{@link rat.rat.Identificateur#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see rat.rat.Identificateur#getId()
   * @see #getIdentificateur()
   * @generated
   */
  EAttribute getIdentificateur_Id();

  /**
   * Returns the meta object for class '{@link rat.rat.Boolean <em>Boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean</em>'.
   * @see rat.rat.Boolean
   * @generated
   */
  EClass getBoolean();

  /**
   * Returns the meta object for the attribute '{@link rat.rat.Boolean#getB <em>B</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>B</em>'.
   * @see rat.rat.Boolean#getB()
   * @see #getBoolean()
   * @generated
   */
  EAttribute getBoolean_B();

  /**
   * Returns the meta object for class '{@link rat.rat.Entier <em>Entier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entier</em>'.
   * @see rat.rat.Entier
   * @generated
   */
  EClass getEntier();

  /**
   * Returns the meta object for the attribute '{@link rat.rat.Entier#getInt <em>Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Int</em>'.
   * @see rat.rat.Entier#getInt()
   * @see #getEntier()
   * @generated
   */
  EAttribute getEntier_Int();

  /**
   * Returns the meta object for class '{@link rat.rat.OpBin <em>Op Bin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Op Bin</em>'.
   * @see rat.rat.OpBin
   * @generated
   */
  EClass getOpBin();

  /**
   * Returns the meta object for the containment reference '{@link rat.rat.OpBin#getE1 <em>E1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E1</em>'.
   * @see rat.rat.OpBin#getE1()
   * @see #getOpBin()
   * @generated
   */
  EReference getOpBin_E1();

  /**
   * Returns the meta object for the containment reference '{@link rat.rat.OpBin#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Op</em>'.
   * @see rat.rat.OpBin#getOp()
   * @see #getOpBin()
   * @generated
   */
  EReference getOpBin_Op();

  /**
   * Returns the meta object for the containment reference '{@link rat.rat.OpBin#getE2 <em>E2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E2</em>'.
   * @see rat.rat.OpBin#getE2()
   * @see #getOpBin()
   * @generated
   */
  EReference getOpBin_E2();

  /**
   * Returns the meta object for class '{@link rat.rat.Operande <em>Operande</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operande</em>'.
   * @see rat.rat.Operande
   * @generated
   */
  EClass getOperande();

  /**
   * Returns the meta object for the attribute '{@link rat.rat.Operande#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see rat.rat.Operande#getOp()
   * @see #getOperande()
   * @generated
   */
  EAttribute getOperande_Op();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RatFactory getRatFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link rat.rat.impl.ProgImpl <em>Prog</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.ProgImpl
     * @see rat.rat.impl.RatPackageImpl#getProg()
     * @generated
     */
    EClass PROG = eINSTANCE.getProg();

    /**
     * The meta object literal for the '<em><b>Fun</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROG__FUN = eINSTANCE.getProg_Fun();

    /**
     * The meta object literal for the '<em><b>Bloc</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROG__BLOC = eINSTANCE.getProg_Bloc();

    /**
     * The meta object literal for the '{@link rat.rat.impl.FunImpl <em>Fun</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.FunImpl
     * @see rat.rat.impl.RatPackageImpl#getFun()
     * @generated
     */
    EClass FUN = eINSTANCE.getFun();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUN__TYPE = eINSTANCE.getFun_Type();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUN__NOM = eINSTANCE.getFun_Nom();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUN__PARAM = eINSTANCE.getFun_Param();

    /**
     * The meta object literal for the '<em><b>Is</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUN__IS = eINSTANCE.getFun_Is();

    /**
     * The meta object literal for the '<em><b>E</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUN__E = eINSTANCE.getFun_E();

    /**
     * The meta object literal for the '{@link rat.rat.impl.BlocImpl <em>Bloc</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.BlocImpl
     * @see rat.rat.impl.RatPackageImpl#getBloc()
     * @generated
     */
    EClass BLOC = eINSTANCE.getBloc();

    /**
     * The meta object literal for the '<em><b>Is</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLOC__IS = eINSTANCE.getBloc_Is();

    /**
     * The meta object literal for the '{@link rat.rat.impl.IImpl <em>I</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.IImpl
     * @see rat.rat.impl.RatPackageImpl#getI()
     * @generated
     */
    EClass I = eINSTANCE.getI();

    /**
     * The meta object literal for the '{@link rat.rat.impl.DeclarationImpl <em>Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.DeclarationImpl
     * @see rat.rat.impl.RatPackageImpl#getDeclaration()
     * @generated
     */
    EClass DECLARATION = eINSTANCE.getDeclaration();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARATION__TYPE = eINSTANCE.getDeclaration_Type();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECLARATION__NOM = eINSTANCE.getDeclaration_Nom();

    /**
     * The meta object literal for the '<em><b>E</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARATION__E = eINSTANCE.getDeclaration_E();

    /**
     * The meta object literal for the '{@link rat.rat.impl.AffectationImpl <em>Affectation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.AffectationImpl
     * @see rat.rat.impl.RatPackageImpl#getAffectation()
     * @generated
     */
    EClass AFFECTATION = eINSTANCE.getAffectation();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AFFECTATION__NOM = eINSTANCE.getAffectation_Nom();

    /**
     * The meta object literal for the '<em><b>E</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AFFECTATION__E = eINSTANCE.getAffectation_E();

    /**
     * The meta object literal for the '{@link rat.rat.impl.ConstanteImpl <em>Constante</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.ConstanteImpl
     * @see rat.rat.impl.RatPackageImpl#getConstante()
     * @generated
     */
    EClass CONSTANTE = eINSTANCE.getConstante();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTANTE__NOM = eINSTANCE.getConstante_Nom();

    /**
     * The meta object literal for the '<em><b>E</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTANTE__E = eINSTANCE.getConstante_E();

    /**
     * The meta object literal for the '{@link rat.rat.impl.PrintImpl <em>Print</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.PrintImpl
     * @see rat.rat.impl.RatPackageImpl#getPrint()
     * @generated
     */
    EClass PRINT = eINSTANCE.getPrint();

    /**
     * The meta object literal for the '<em><b>E</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRINT__E = eINSTANCE.getPrint_E();

    /**
     * The meta object literal for the '{@link rat.rat.impl.ConditionnelleImpl <em>Conditionnelle</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.ConditionnelleImpl
     * @see rat.rat.impl.RatPackageImpl#getConditionnelle()
     * @generated
     */
    EClass CONDITIONNELLE = eINSTANCE.getConditionnelle();

    /**
     * The meta object literal for the '<em><b>E</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITIONNELLE__E = eINSTANCE.getConditionnelle_E();

    /**
     * The meta object literal for the '<em><b>Bloc1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITIONNELLE__BLOC1 = eINSTANCE.getConditionnelle_Bloc1();

    /**
     * The meta object literal for the '<em><b>Bloc2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITIONNELLE__BLOC2 = eINSTANCE.getConditionnelle_Bloc2();

    /**
     * The meta object literal for the '{@link rat.rat.impl.TantqueImpl <em>Tantque</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.TantqueImpl
     * @see rat.rat.impl.RatPackageImpl#getTantque()
     * @generated
     */
    EClass TANTQUE = eINSTANCE.getTantque();

    /**
     * The meta object literal for the '<em><b>E</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TANTQUE__E = eINSTANCE.getTantque_E();

    /**
     * The meta object literal for the '<em><b>Bloc</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TANTQUE__BLOC = eINSTANCE.getTantque_Bloc();

    /**
     * The meta object literal for the '{@link rat.rat.impl.DPImpl <em>DP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.DPImpl
     * @see rat.rat.impl.RatPackageImpl#getDP()
     * @generated
     */
    EClass DP = eINSTANCE.getDP();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DP__TYPE = eINSTANCE.getDP_Type();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DP__ID = eINSTANCE.getDP_Id();

    /**
     * The meta object literal for the '{@link rat.rat.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.TypeImpl
     * @see rat.rat.impl.RatPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>T</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__T = eINSTANCE.getType_T();

    /**
     * The meta object literal for the '{@link rat.rat.impl.CPImpl <em>CP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.CPImpl
     * @see rat.rat.impl.RatPackageImpl#getCP()
     * @generated
     */
    EClass CP = eINSTANCE.getCP();

    /**
     * The meta object literal for the '<em><b>E</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CP__E = eINSTANCE.getCP_E();

    /**
     * The meta object literal for the '{@link rat.rat.impl.EImpl <em>E</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.EImpl
     * @see rat.rat.impl.RatPackageImpl#getE()
     * @generated
     */
    EClass E = eINSTANCE.getE();

    /**
     * The meta object literal for the '{@link rat.rat.impl.AppelImpl <em>Appel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.AppelImpl
     * @see rat.rat.impl.RatPackageImpl#getAppel()
     * @generated
     */
    EClass APPEL = eINSTANCE.getAppel();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute APPEL__NOM = eINSTANCE.getAppel_Nom();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APPEL__PARAM = eINSTANCE.getAppel_Param();

    /**
     * The meta object literal for the '{@link rat.rat.impl.RationnelImpl <em>Rationnel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.RationnelImpl
     * @see rat.rat.impl.RatPackageImpl#getRationnel()
     * @generated
     */
    EClass RATIONNEL = eINSTANCE.getRationnel();

    /**
     * The meta object literal for the '<em><b>E1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RATIONNEL__E1 = eINSTANCE.getRationnel_E1();

    /**
     * The meta object literal for the '<em><b>E2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RATIONNEL__E2 = eINSTANCE.getRationnel_E2();

    /**
     * The meta object literal for the '{@link rat.rat.impl.NumerateurImpl <em>Numerateur</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.NumerateurImpl
     * @see rat.rat.impl.RatPackageImpl#getNumerateur()
     * @generated
     */
    EClass NUMERATEUR = eINSTANCE.getNumerateur();

    /**
     * The meta object literal for the '<em><b>E</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NUMERATEUR__E = eINSTANCE.getNumerateur_E();

    /**
     * The meta object literal for the '{@link rat.rat.impl.DenominateurImpl <em>Denominateur</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.DenominateurImpl
     * @see rat.rat.impl.RatPackageImpl#getDenominateur()
     * @generated
     */
    EClass DENOMINATEUR = eINSTANCE.getDenominateur();

    /**
     * The meta object literal for the '<em><b>E</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DENOMINATEUR__E = eINSTANCE.getDenominateur_E();

    /**
     * The meta object literal for the '{@link rat.rat.impl.IdentificateurImpl <em>Identificateur</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.IdentificateurImpl
     * @see rat.rat.impl.RatPackageImpl#getIdentificateur()
     * @generated
     */
    EClass IDENTIFICATEUR = eINSTANCE.getIdentificateur();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IDENTIFICATEUR__ID = eINSTANCE.getIdentificateur_Id();

    /**
     * The meta object literal for the '{@link rat.rat.impl.BooleanImpl <em>Boolean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.BooleanImpl
     * @see rat.rat.impl.RatPackageImpl#getBoolean()
     * @generated
     */
    EClass BOOLEAN = eINSTANCE.getBoolean();

    /**
     * The meta object literal for the '<em><b>B</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN__B = eINSTANCE.getBoolean_B();

    /**
     * The meta object literal for the '{@link rat.rat.impl.EntierImpl <em>Entier</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.EntierImpl
     * @see rat.rat.impl.RatPackageImpl#getEntier()
     * @generated
     */
    EClass ENTIER = eINSTANCE.getEntier();

    /**
     * The meta object literal for the '<em><b>Int</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTIER__INT = eINSTANCE.getEntier_Int();

    /**
     * The meta object literal for the '{@link rat.rat.impl.OpBinImpl <em>Op Bin</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.OpBinImpl
     * @see rat.rat.impl.RatPackageImpl#getOpBin()
     * @generated
     */
    EClass OP_BIN = eINSTANCE.getOpBin();

    /**
     * The meta object literal for the '<em><b>E1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OP_BIN__E1 = eINSTANCE.getOpBin_E1();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OP_BIN__OP = eINSTANCE.getOpBin_Op();

    /**
     * The meta object literal for the '<em><b>E2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OP_BIN__E2 = eINSTANCE.getOpBin_E2();

    /**
     * The meta object literal for the '{@link rat.rat.impl.OperandeImpl <em>Operande</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see rat.rat.impl.OperandeImpl
     * @see rat.rat.impl.RatPackageImpl#getOperande()
     * @generated
     */
    EClass OPERANDE = eINSTANCE.getOperande();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERANDE__OP = eINSTANCE.getOperande_Op();

  }

} //RatPackage
