/**
 * generated by Xtext 2.12.0
 */
package rat.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import rat.ui.AbstractRatUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RatUiModule extends AbstractRatUiModule {
  public RatUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
