/*
 * generated by Xtext 2.16.0
 */
package rat.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import rat.ui.internal.RatActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RatExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(RatActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		RatActivator activator = RatActivator.getInstance();
		return activator != null ? activator.getInjector(RatActivator.RAT_RAT) : null;
	}

}
