/**
 * generated by Xtext 2.12.0
 */
package rat.ui.contentassist;

import rat.ui.contentassist.AbstractRatProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RatProposalProvider extends AbstractRatProposalProvider {
}
