/**
 * generated by Xtext 2.12.0
 */
package rat.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import rat.RatRuntimeModule;
import rat.RatStandaloneSetup;
import rat.ide.RatIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RatIdeSetup extends RatStandaloneSetup {
  @Override
  public Injector createInjector() {
    RatRuntimeModule _ratRuntimeModule = new RatRuntimeModule();
    RatIdeModule _ratIdeModule = new RatIdeModule();
    return Guice.createInjector(Modules2.mixin(_ratRuntimeModule, _ratIdeModule));
  }
}
