/**
 * generated by Xtext 2.12.0
 */
package rat;

import rat.AbstractRatRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RatRuntimeModule extends AbstractRatRuntimeModule {
}
